version: '3'
# ---------------------------------------------------------
# ---------------------------------------------------------
services:
# ---------------------------------------------------------
  postgres_fastapi:
    image: postgres:latest
    volumes:
      - ./postgres_fastapi_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: pgadmin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
# ---------------------------------------------------------
  postgres_keycloak:
    image: postgres:latest
    volumes:
      - ./postgres_keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
# ---------------------------------------------------------
# ---------------------------------------------------------
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL : admin@admin.com
      PGADMIN_DEFAULT_PASSWORD : admin
    depends_on:
      - postgres_fastapi
# ---------------------------------------------------------
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak_data:/opt/jboss/keycloak/standalone/data/
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres_keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: https://keycloak/auth
    depends_on:
      - postgres_keycloak
# ---------------------------------------------------------
  openldap:
    image: osixia/openldap
    volumes:
      - ./openldap_data:/var/lib/ldap
      - ./openldap_conf:/etc/ldap/slapd.d
    environment:
      LDAP_ADMIN_PASSWORD: password
      LDAP_BASE_DN: dc=imolinfo,dc=it
      LDAP_CONFIG_PASSWORD: password
      LDAP_DOMAIN: imolinfo.it
      LDAP_READONLY_USER_PASSWORD: password
      LDAP_READONLY_USER_USERNAME: readonly
      LDAP_ORGANISATION: Imola Informatica
      LDAP_TLS: 'false'
# ---------------------------------------------------------
  phpldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
    ports:
      - 6443:443
    depends_on:
      - openldap
# ---------------------------------------------------------
# ---------------------------------------------------------
  fastapi:
    build:
      context: ./fastapi_data
      dockerfile: ./Dockerfile
    volumes:
      - ./fastapi_data:/fastapi_data
      -  /etc/localtime:/etc/localtime:ro
      - ./fastapi_data/ssh:/root/.ssh
    depends_on:
      - postgres_fastapi
      - keycloak
# ---------------------------------------------------------
  fastapi_testing:
    build:
      context: ./fastapi_testing_data
      dockerfile: ./Dockerfile
    volumes:
      - ./fastapi_data:/fastapi_data
      - ./fastapi_testing_data:/fastapi_testing_data
      -  /etc/localtime:/etc/localtime:ro
      - ./fastapi_data/ssh:/root/.ssh
    depends_on:
      - postgres_fastapi
      - keycloak
# ---------------------------------------------------------
# ---------------------------------------------------------
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime:ro
      - ./certificates:/etc/nginx/ssl/
    depends_on:
      - postgres_fastapi
      - postgres_keycloak
      - pgadmin
      - keycloak
      - openldap
      - phpldapadmin
      - fastapi
      - fastapi_testing
    ports:
      - 80:80
      - 443:443
